### ISSUE TITLE
Leaflet Integration

### ISSUE THREAD

**Issue by JustinCally** [JustinCally/VicmapR#20]
Integrate VicmapR into a leaflet workflow so that layers can be easily added as tiles and formatted in similar ways as `leaflet::addWMSTiles()`. 

## Tasks: 

- [ ] Add one tile  and customize it 
- [ ] Add a collection of tiles from a datavic prefix (e.g. hydro) 
- [ ] Find default schemes for colouring etc.
